%% Simple script to test the Inventory class.

% This is set to trip check_for_problems.
% Use a higher reorder point and request batch size to avoid that.
inventory = Inventory( ...
    OnHand=50, ...
    RequestCostPerBatch=25.0, ...
    RequestCostPerUnit=3.0, ...
    HoldingCostPerUnitPerDay=0.05/7, ...
    ShortageCostPerUnitPerDay=2.00/7, ...
    RequestBatchSize=50, ...
    ReorderPoint=10, ...
    RequestLeadTime=2, ...
    OutgoingSizeDist=makedist("Gamma", a=10, b=2), ...
    DailyOrderCountDist=makedist("Poisson", lambda=4));
run_until(inventory, 500);
