%% Simple script to test the Inventory class.
inventory = Inventory( ...
    OnHand=600, ...
    RequestCostPerBatch=25.0, ...
    RequestCostPerUnit=3.0, ...
    HoldingCostPerUnitPerDay=0.05/7, ...
    ShortageCostPerUnitPerDay=2.00/7, ...
    RequestBatchSize=300, ...
    ReorderPoint=100, ...
    RequestLeadTime=2, ...
    OutgoingSizeDist=makedist("Gamma", a=10, b=2), ...
    DailyOrderCountDist=makedist("Poisson", lambda=4));
run_until(inventory, 100);
